In [1]:
# Load an initialize a bunch of things (including pyrosetta)
# It also automatically suppresses a lot of input. You can edit the init() call in General to change this behaviour (or comment it out and manually initialize here)
%run ../PyRosetta/General.ipynb # May need to give absolute path if notebook is elsewhere


┌──────────────────────────────────────────────────────────────────────────────┐
│                                 PyRosetta-4                                  │
│              Created in JHU by Sergey Lyskov and PyRosetta Team              │
│              (C) Copyright Rosetta Commons Member Institutions               │
│                                                                              │
│ NOTE: USE OF PyRosetta FOR COMMERCIAL PURPOSES REQUIRE PURCHASE OF A LICENSE │
│              See LICENSE.md or email license@uw.edu for details              │
└──────────────────────────────────────────────────────────────────────────────┘
PyRosetta-4 2024 [Rosetta PyRosetta4.Release.python310.linux 2024.08+release.717d2e8232174371f0c672564f23a097062db88a 2024-02-21T10:16:44] retrieved from: http://www.pyrosetta.org


## Introducing LoadedPDB

In [2]:
# LoadedPDB: A wrapper around pyrosetta.rosetta.core.pose.Pose
pose=LoadedPDB("PDBs/7qr4_clean.pdb")
type(pose)

__main__.LoadedPDB

In [3]:
# LoadedPDB can also directly be initialized from a Pose object
pose_obj=pyrosetta.pose_from_pdb("PDBs/7qr4_clean.pdb")
copied_pose=LoadedPDB(pose_obj)
print(type(pose_obj),type(copied_pose))

<class 'pyrosetta.rosetta.core.pose.Pose'> <class '__main__.LoadedPDB'>


### Regular functionality

In [4]:
# All regular Pose object functionality is available:
print("Sequence:")
print(pose.sequence(),"\n")
print("Conformation:")
print(pose.conformation(),"\n")
print("Picking out residues:")
print(pose.residue(5),"\n")

# Write Pose to PDB file
_=pose.dump_pdb("example.pdb")

Sequence:
gggggccacagcagaagcguucacgucgcagccccugucagccauugcacuccggcugcgaauucugcu 

Conformation:
RESCON: 1 RGU:LowerRNA:Virtual_Phosphate n-conn= 1 n-poly= 1 n-nonpoly= 0 conn# 1 9 2 1
RESCON: 2 RGU n-conn= 2 n-poly= 2 n-nonpoly= 0 conn# 1 1 1 1 conn# 2 9 3 1
RESCON: 3 RGU n-conn= 2 n-poly= 2 n-nonpoly= 0 conn# 1 1 2 2 conn# 2 9 4 1
RESCON: 4 RGU n-conn= 2 n-poly= 2 n-nonpoly= 0 conn# 1 1 3 2 conn# 2 9 5 1
RESCON: 5 RGU n-conn= 2 n-poly= 2 n-nonpoly= 0 conn# 1 1 4 2 conn# 2 9 6 1
RESCON: 6 RCY n-conn= 2 n-poly= 2 n-nonpoly= 0 conn# 1 1 5 2 conn# 2 9 7 1
RESCON: 7 RCY n-conn= 2 n-poly= 2 n-nonpoly= 0 conn# 1 1 6 2 conn# 2 9 8 1
RESCON: 8 RAD n-conn= 2 n-poly= 2 n-nonpoly= 0 conn# 1 1 7 2 conn# 2 9 9 1
RESCON: 9 RCY n-conn= 2 n-poly= 2 n-nonpoly= 0 conn# 1 1 8 2 conn# 2 9 10 1
RESCON: 10 RAD n-conn= 2 n-poly= 2 n-nonpoly= 0 conn# 1 1 9 2 conn# 2 9 11 1
RESCON: 11 RGU n-conn= 2 n-poly= 2 n-nonpoly= 0 conn# 1 1 10 2 conn# 2 9 12 1
RESCON: 12 RCY n-conn= 2 n-poly= 2 n-nonpoly= 0 conn# 1 1 11

### Extra options

In [5]:
# Count residues
print("No of residues:",len(pose))

# Iterate over residues
print("Iterating to get sequence:",end="\t")
for res in pose:
    print(res.name1(),end="") # Prints out 1-letter code for each residue
print()

# Batch request key angles:
print("Alphas:",pose.generic_all("alpha")[:5]) # All 'alpha' angles for each residue of RNA (Truncated for brevity)
print("Zetas:",pose.generic_all("zeta")[:5]) # All 'zeta' angles for each residue of RNA (Truncated for brevity)

# Find all atom indices that satisfy a given requirement (atoms are indexed from 1 ... N, sorted first by residue number, then within the residue)
print("All H atoms:",pose.hydrogen_indices()[-5:]) # Indices of all hydrogen atoms (truncated for brevity)
print("All C2 atoms:",pose.matching_indices(lambda res,idx: res.atom_name(idx).strip()=="C2")[-5:]) # Indices of all C2 atoms (truncated for brevity)

No of residues: 69
Iterating to get sequence:	gggggccacagcagaagcguucacgucgcagccccugucagccauugcacuccggcugcgaauucugcu
Alphas: [  0.         -57.83213223 -35.99942742 -59.79865542 -68.31282507]
Zetas: [ -79.39541652 -103.74819728  -87.83606941  -75.71824248  -93.58806413]
All H atoms: [2205 2206 2207 2208 2209]
All C2 atoms: [2067 2098 2128 2162 2193]


### Complex tasks
Still under development. More tasks are being added everyday

In [6]:
#Get all g-vectors
print(pose.get_gmat()) # Default cut-off (24 A - chosen from barnaba)

[[[ 0.          0.          0.          0.        ]
  [-0.19939528  2.26277955  7.16698604  6.28467412]
  [ 0.          0.          0.          0.        ]
  ...
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]]

 [[-2.66478286 -1.90334751 -6.88384963  7.13962068]
  [ 0.          0.          0.          0.        ]
  [ 2.95098735  2.26405313  6.64913453  8.20135269]
  ...
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]]

 [[ 0.          0.          0.          0.        ]
  [-3.49957006 -0.20016804 -6.7781188   8.00144482]
  [ 0.          0.          0.          0.        ]
  ...
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]]

 ...

 [[ 0.          0.          0.    

In [7]:
# Get all atom coordinates as a torch tensor (Useful for training)
print("Atom coordinates:",get_torch_rep(pose).shape) # By default it ignores H-atoms
print("Atom coordinates (H atoms included):",get_torch_rep(pose,ignore_Hs=False).shape)

Atom coordinates: torch.Size([1466, 3])
Atom coordinates (H atoms included): torch.Size([2210, 3])


In [8]:
# 3D alignment (minimized RMSD under rigid-body re-orientation)
# Still needs to be verified if working correctly
to_align=LoadedPDB("PDBs/rosetta_0.pdb")
aligned_pose=align_poses(ref_struct=pose,pose_struct=to_align,max_iter=1000,silent=False,printevery=100)
type(aligned_pose)

0 1419.093994140625
100 1308.368408203125
200 1184.1339111328125
300 1058.693359375
400 944.8593139648438
500 851.0695190429688
600 779.6177368164062
700 728.1978759765625
800 692.498291015625
900 668.1277465820312


pyrosetta.rosetta.core.pose.Pose

In [11]:
# Get RMSD (No Alignment is done. Matching Atoms are assumed to be in the same order for both structures, with no atoms/residues missing)
# It is OK if some atoms/residues are missing if the EXACT SAME are missing from the other structure

print("Before alignment:",get_rmsd(pose,to_align)) # Ignores H-atoms (usually not a big difference for RNA)
print("After alignment:",get_rmsd(pose,aligned_pose)) # Ignores H-atoms (usually not a big difference for RNA)
#Note: Results are in Angstroms

Before alignment: 47.998592246246126
After alignment: 25.52419996092638
